/* Generated By:JavaCC: Do not edit this line. CCSQLiteQueryParserConstants.java */
package javacc.sqlitequeryparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCSQLiteQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_CREATE_TABLE = 7;
  /** RegularExpression Id. */
  int T_OPEN_BRACKET = 8;
  /** RegularExpression Id. */
  int T_CLOSE_BRACKET = 9;
  /** RegularExpression Id. */
  int T_COMMA = 10;
  /** RegularExpression Id. */
  int T_PRIMARY_KEY = 11;
  /** RegularExpression Id. */
  int T_AUTOINCREMENT = 12;
  /** RegularExpression Id. */
  int T_NOT = 13;
  /** RegularExpression Id. */
  int T_NULL = 14;
  /** RegularExpression Id. */
  int T_IF = 15;
  /** RegularExpression Id. */
  int T_EXISTS = 16;
  /** RegularExpression Id. */
  int T_UNIQUE = 17;
  /** RegularExpression Id. */
  int T_DEFAULT = 18;
  /** RegularExpression Id. */
  int T_APOSTR = 19;
  /** RegularExpression Id. */
  int T_CONSTRAINT = 20;
  /** RegularExpression Id. */
  int T_ON = 21;
  /** RegularExpression Id. */
  int T_CONFLICT = 22;
  /** RegularExpression Id. */
  int T_ROLLBACK = 23;
  /** RegularExpression Id. */
  int T_ABORT = 24;
  /** RegularExpression Id. */
  int T_FAIL = 25;
  /** RegularExpression Id. */
  int T_IGNORE = 26;
  /** RegularExpression Id. */
  int T_REPLACE = 27;
  /** RegularExpression Id. */
  int T_FOREIGN_KEY = 28;
  /** RegularExpression Id. */
  int T_REFERENCES = 29;
  /** RegularExpression Id. */
  int T_DELETE = 30;
  /** RegularExpression Id. */
  int T_UPDATE = 31;
  /** RegularExpression Id. */
  int T_SET = 32;
  /** RegularExpression Id. */
  int T_CASCADE = 33;
  /** RegularExpression Id. */
  int T_RESTRICT = 34;
  /** RegularExpression Id. */
  int T_NO = 35;
  /** RegularExpression Id. */
  int T_ACTION = 36;
  /** RegularExpression Id. */
  int T_DEFERRABLE = 37;
  /** RegularExpression Id. */
  int T_INITIALLY = 38;
  /** RegularExpression Id. */
  int T_DEFERRED = 39;
  /** RegularExpression Id. */
  int T_IMMEDIATE = 40;
  /** RegularExpression Id. */
  int T_IDENTIFIER = 41;
  /** RegularExpression Id. */
  int LETTER = 42;
  /** RegularExpression Id. */
  int NUMBER = 43;
  /** RegularExpression Id. */
  int T_QUOTED_IDENTIFIER = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "\"CREATE TABLE\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"PRIMARY KEY\"",
    "\"AUTOINCREMENT\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"IF\"",
    "\"EXISTS\"",
    "\"UNIQUE\"",
    "\"DEFAULT\"",
    "<T_APOSTR>",
    "\"CONSTRAINT\"",
    "\"ON\"",
    "\"CONFLICT\"",
    "\"ROLLBACK\"",
    "\"ABORT\"",
    "\"FAIL\"",
    "\"IGNORE\"",
    "\"REPLACE\"",
    "\"FOREIGN KEY\"",
    "\"REFERENCES\"",
    "\"DELETE\"",
    "\"UPDATE\"",
    "\"SET\"",
    "\"CASCADE\"",
    "\"RESTRICT\"",
    "\"NO\"",
    "\"ACTION\"",
    "\"DEFERRABLE\"",
    "\"INITIALLY\"",
    "\"DEFERRED\"",
    "\"IMMEDIATE\"",
    "<T_IDENTIFIER>",
    "<LETTER>",
    "<NUMBER>",
    "<T_QUOTED_IDENTIFIER>",
    "\".\"",
  };

}
