/* Generated By:JavaCC: Do not edit this line. CCSQLiteQueryParserConstants.java */
package javacc.sqlitequeryparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCSQLiteQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int INTEGER = 8;
  /** RegularExpression Id. */
  int SGN = 9;
  /** RegularExpression Id. */
  int REAL = 10;
  /** RegularExpression Id. */
  int TEXT = 11;
  /** RegularExpression Id. */
  int BLOB = 12;
  /** RegularExpression Id. */
  int HEX = 13;
  /** RegularExpression Id. */
  int T_CREATE = 14;
  /** RegularExpression Id. */
  int T_TABLE = 15;
  /** RegularExpression Id. */
  int T_DROP = 16;
  /** RegularExpression Id. */
  int T_OPEN_BRACKET = 17;
  /** RegularExpression Id. */
  int T_CLOSE_BRACKET = 18;
  /** RegularExpression Id. */
  int T_COMMA = 19;
  /** RegularExpression Id. */
  int T_PRIMARY = 20;
  /** RegularExpression Id. */
  int T_KEY = 21;
  /** RegularExpression Id. */
  int T_AUTOINCREMENT = 22;
  /** RegularExpression Id. */
  int T_NOT = 23;
  /** RegularExpression Id. */
  int T_NULL = 24;
  /** RegularExpression Id. */
  int T_IF = 25;
  /** RegularExpression Id. */
  int T_EXISTS = 26;
  /** RegularExpression Id. */
  int T_UNIQUE = 27;
  /** RegularExpression Id. */
  int T_INDEX = 28;
  /** RegularExpression Id. */
  int T_DEFAULT = 29;
  /** RegularExpression Id. */
  int T_APOSTR = 30;
  /** RegularExpression Id. */
  int T_CONSTRAINT = 31;
  /** RegularExpression Id. */
  int T_ON = 32;
  /** RegularExpression Id. */
  int T_CONFLICT = 33;
  /** RegularExpression Id. */
  int T_ROLLBACK = 34;
  /** RegularExpression Id. */
  int T_ABORT = 35;
  /** RegularExpression Id. */
  int T_FAIL = 36;
  /** RegularExpression Id. */
  int T_IGNORE = 37;
  /** RegularExpression Id. */
  int T_REPLACE = 38;
  /** RegularExpression Id. */
  int T_FOREIGN = 39;
  /** RegularExpression Id. */
  int T_REFERENCES = 40;
  /** RegularExpression Id. */
  int T_DELETE = 41;
  /** RegularExpression Id. */
  int T_UPDATE = 42;
  /** RegularExpression Id. */
  int T_SET = 43;
  /** RegularExpression Id. */
  int T_CASCADE = 44;
  /** RegularExpression Id. */
  int T_RESTRICT = 45;
  /** RegularExpression Id. */
  int T_NO = 46;
  /** RegularExpression Id. */
  int T_ACTION = 47;
  /** RegularExpression Id. */
  int T_DEFERRABLE = 48;
  /** RegularExpression Id. */
  int T_INITIALLY = 49;
  /** RegularExpression Id. */
  int T_DEFERRED = 50;
  /** RegularExpression Id. */
  int T_IMMEDIATE = 51;
  /** RegularExpression Id. */
  int T_ASC = 52;
  /** RegularExpression Id. */
  int T_DESC = 53;
  /** RegularExpression Id. */
  int T_ALTER = 54;
  /** RegularExpression Id. */
  int T_ADD = 55;
  /** RegularExpression Id. */
  int T_COLUMN = 56;
  /** RegularExpression Id. */
  int T_RENAME = 57;
  /** RegularExpression Id. */
  int T_TO = 58;
  /** RegularExpression Id. */
  int T_INSERT = 59;
  /** RegularExpression Id. */
  int T_INTO = 60;
  /** RegularExpression Id. */
  int T_VALUES = 61;
  /** RegularExpression Id. */
  int T_IDENTIFIER = 62;
  /** RegularExpression Id. */
  int LETTER = 63;
  /** RegularExpression Id. */
  int NUMBER = 64;
  /** RegularExpression Id. */
  int T_QUOTED_IDENTIFIER = 65;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "<DIGIT>",
    "<INTEGER>",
    "<SGN>",
    "<REAL>",
    "<TEXT>",
    "<BLOB>",
    "<HEX>",
    "\"CREATE\"",
    "\"TABLE\"",
    "\"DROP\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"PRIMARY\"",
    "\"KEY\"",
    "\"AUTOINCREMENT\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"IF\"",
    "\"EXISTS\"",
    "\"UNIQUE\"",
    "\"INDEX\"",
    "\"DEFAULT\"",
    "<T_APOSTR>",
    "\"CONSTRAINT\"",
    "\"ON\"",
    "\"CONFLICT\"",
    "\"ROLLBACK\"",
    "\"ABORT\"",
    "\"FAIL\"",
    "\"IGNORE\"",
    "\"REPLACE\"",
    "\"FOREIGN\"",
    "\"REFERENCES\"",
    "\"DELETE\"",
    "\"UPDATE\"",
    "\"SET\"",
    "\"CASCADE\"",
    "\"RESTRICT\"",
    "\"NO\"",
    "\"ACTION\"",
    "\"DEFERRABLE\"",
    "\"INITIALLY\"",
    "\"DEFERRED\"",
    "\"IMMEDIATE\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"ALTER\"",
    "\"ADD\"",
    "\"COLUMN\"",
    "\"RENAME\"",
    "\"TO\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"VALUES\"",
    "<T_IDENTIFIER>",
    "<LETTER>",
    "<NUMBER>",
    "<T_QUOTED_IDENTIFIER>",
    "\";\"",
    "\".\"",
  };

}
