/* Generated By:JavaCC: Do not edit this line. CCSQLiteQueryParserConstants.java */
package javacc.sqlitequeryparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCSQLiteQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_CREATE_TABLE = 7;
  /** RegularExpression Id. */
  int T_OPEN_BRACKET = 8;
  /** RegularExpression Id. */
  int T_CLOSE_BRACKET = 9;
  /** RegularExpression Id. */
  int T_COMMA = 10;
  /** RegularExpression Id. */
  int T_PRIMARY_KEY = 11;
  /** RegularExpression Id. */
  int T_AUTOINCREMENT = 12;
  /** RegularExpression Id. */
  int T_NOT = 13;
  /** RegularExpression Id. */
  int T_NULL = 14;
  /** RegularExpression Id. */
  int T_IF = 15;
  /** RegularExpression Id. */
  int T_EXISTS = 16;
  /** RegularExpression Id. */
  int T_UNIQUE = 17;
  /** RegularExpression Id. */
  int T_DEFAULT = 18;
  /** RegularExpression Id. */
  int T_APOSTR = 19;
  /** RegularExpression Id. */
  int T_IDENTIFIER = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int NUMBER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "\"CREATE TABLE\"",
    "<T_OPEN_BRACKET>",
    "<T_CLOSE_BRACKET>",
    "\",\"",
    "\"PRIMARY KEY\"",
    "\"AUTOINCREMENT\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"IF\"",
    "\"EXISTS\"",
    "\"UNIQUE\"",
    "\"DEFAULT\"",
    "\"\\\'\"",
    "<T_IDENTIFIER>",
    "<LETTER>",
    "<NUMBER>",
    "\".\"",
  };

}
